# Patch generated by Pyment v0.3.3

--- a/..//venv/lib/python3.8/site-packages/pandas/tests/indexing/multiindex/test_multiindex.py
+++ b/..//venv/lib/python3.8/site-packages/pandas/tests/indexing/multiindex/test_multiindex.py
@@ -10,7 +10,9 @@
 
 
 class TestMultiIndexBasic:
+    """ """
     def test_multiindex_perf_warn(self):
+        """ """
 
         df = DataFrame(
             {
@@ -28,6 +30,7 @@
             df.loc[(0,)]
 
     def test_indexing_over_hashtable_size_cutoff(self):
+        """ """
         n = 10000
 
         old_cutoff = _index._SIZE_CUTOFF
@@ -43,6 +46,7 @@
         _index._SIZE_CUTOFF = old_cutoff
 
     def test_multi_nan_indexing(self):
+        """ """
 
         # GH 3588
         df = DataFrame(
@@ -67,6 +71,7 @@
         tm.assert_frame_equal(result, expected)
 
     def test_nested_tuples_duplicates(self):
+        """ """
         # GH#30892
 
         dti = pd.to_datetime(["20190101", "20190101", "20190102"])
@@ -86,6 +91,7 @@
         tm.assert_frame_equal(df3, expected)
 
     def test_multiindex_get_loc_list_raises(self):
+        """ """
         # https://github.com/pandas-dev/pandas/issues/35878
         idx = pd.MultiIndex.from_tuples([("a", 1), ("b", 2)])
         msg = "unhashable type"
