# Patch generated by Pyment v0.3.3

--- a/..//venv/lib/python3.8/site-packages/numpy/core/tests/test_protocols.py
+++ b/..//venv/lib/python3.8/site-packages/numpy/core/tests/test_protocols.py
@@ -5,9 +5,11 @@
 
 @pytest.mark.filterwarnings("error")
 def test_getattr_warning():
+    """ """
     # issue gh-14735: make sure we clear only getattr errors, and let warnings
     # through
     class Wrapper:
+        """ """
         def __init__(self, array):
             self.array = array
 
@@ -32,7 +34,9 @@
 
 
 def test_array_called():
+    """ """
     class Wrapper:
+        """ """
         val = '0' * 100
         def __array__(self, result=None):
             return np.array([self.val], dtype=object)
